pipeline:
  build:
    image: golang:1.8.3
    environment:
      - CGO=0
      - GOOS=linux
      - GOARCH=amd64
    commands:
      - go build -o hello-world .

  build-image:
    image: plugins/docker
    registry: quay.io
    repo: quay.io/bakins/hello-world
    secrets: [ docker_username, docker_password ]
    tags: ${DRONE_COMMIT_SHA:0:8}
    debug: true
    when:
      branch: master

  deploy-app:
    image: quay.io/bakins/k8s-deployer:2e452fb
    secrets: [ kubeconfig ]
    commands:
      - "./script/deploy quay.io/bakins/hello-world:${DRONE_COMMIT_SHA:0:8}"
    when:
      branch: master

