pipeline:
  build:
    image: golang:1.8.3
    environment:
      - CGO=0
      - GOOS=linux
      - GOARCH=amd64
    commands:
      - go build -o hello-world .

  build-image:
    image: plugins/docker
    repo: dockerfactory.rsglab.com/bakins/hello-world
    tags: ${DRONE_COMMIT_SHA:0:8}
    when:
      branch: master

  deploy-app:
    image: dockerfactory.rsglab.com/rsg/platform/k8s-deployer:cb2ccd3-39
    commands:
      - kaml --set=image=dockerfactory.rsglab.com/bakins/hello-world:${DRONE_COMMIT_SHA:0:8} ./pando local
    when:
      branch: master

