pipeline:
#  build:
#    image: golang:1.8.3
#    environment:
#      - CGO=0
#      - GOOS=linux
#      - GOARCH=amd64
#    commands:
#      - go build -o hello-world .

  docker:
    image: ubuntu
    commands:
     - echo $DOCKER_USERNAME
     - echo $DOCKER_PASSWORD
    secrets: [ docker_username, docker_password ]

  build-image:
    image: plugins/docker
    repo: quay.io/bakins/hello-world
    secrets: [ docker_username, docker_password ]
    tags: ${DRONE_COMMIT_SHA:0:8}
    debug: true
    when:
      branch: master

  deploy-app:
    image: dockerfactory.rsglab.com/rsg/platform/k8s-deployer:cb2ccd3-39
    commands:
      - "kaml --set=image=quay.io/bakins/hello-world:${DRONE_COMMIT_SHA:0:8} ./pando local"
    when:
      branch: master

